# Generated by Django 3.1.7 on 2022-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=128, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('state', models.IntegerField(choices=[(1, '超级管理员'), (2, '发布员'), (3, '审核员'), (-1, '无效用户'), (-2, '删除账号')], db_index=True, default=1, verbose_name='用户状态')),
                ('last_login', models.DateTimeField(db_index=True, null=True, verbose_name='上次登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
